<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format2.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>hande_control</name>
    <version>0.0.0</version>
    <description>The controller of ROS2 humble package for hand-e.</description>
    <maintainer email="taku8926@gmail.com">Takuya Kiyokawa</maintainer>
    <license>BSD</license>

    <!-- Package runtime and build dependencies -->
    <depend>rclpy</depend>
    <depend>launch</depend>
    <depend>launch_ros</depend>
    <depend>controller_manager</depend>
    <depend>joint_state_broadcaster</depend>
    <depend>joint_trajectory_controller</depend>
    <depend>ros2_control</depend>

    <export>
        <build_type>ament_python</build_type>
    </export>
</package>