<?xml version="1.0"?>
<package format="2">
  <name>hande_description</name>
  <version>0.0.0</version>
  <description>Hand-E description files</description>
  <author email="taku8926@gmail.com">Takuya Kiyokawa</author>
  <maintainer email="taku8926@gmail.com">Takuya Kiyokawa</maintainer>
  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <depend>urdf</depend>
  <depend>rospy</depend>
  <depend>std_msgs</depend>
</package>
